name: Build PEMF Tracks

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'package.json'
      - 'Makefile'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'package.json'
      - 'Makefile'

jobs:
  no-code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No code changes detected; skipping build."