name: Docs checks

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'
      - '.lychee.toml'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'
      - '.lychee.toml'
      - '.github/workflows/docs.yml'

jobs:
  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
          config: .markdownlint.jsonc

  lychee:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --config .lychee.toml
            --no-progress
            --accept 200,206,429
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}